name: Generate Snake

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Soumya9001
          outputs: |
            profile/snake.svg?color_theme=green

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/
          git diff --staged --quiet || git commit -m "Update snake animation [skip ci]"
          git push
